# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_internprjpawallactivity_internprjpawdrillact_internprjpawseisact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internprjpawallactivity',
            options={'managed': True},
        ),
    ]
