# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_accountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('insert_date', models.DateField(blank=True, null=True)),
                ('insert_user', models.CharField(blank=True, max_length=64, null=True)),
                ('produced_by', models.CharField(blank=True, max_length=64, null=True)),
                ('sdat_label', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=64, null=True)),
                ('existence_kind', models.CharField(max_length=64)),
                ('guid', models.CharField(blank=True, max_length=128, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_source', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('bulk_coordinate_system_id', models.BigIntegerField(blank=True, null=True)),
                ('bulk_data_id', models.BigIntegerField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area_',
                'managed': False,
            },
        ),
    ]
